### ISSUE TITLE
add support for BSONObjectID

### ISSUE THREAD

**Issue by zy4** [circe/circe-bson#2]
At the moment this BSONValue type is not supported. Since I am moving from `play-json` to circe in one project and there has been a support for this type in the `reactivemongo.play.json` library, it would be nice to have it here as well.

**Comment by zy4** [comment]
closed with 10566b04b95ca43787b654f087899e923f2f550f

**Comment by dkovalenko** [comment]
Have you published artifact with this fix?

**Comment by dkovalenko** [comment]
@travisbrown can we publish version with this fix ?

**Comment by travisbrown** [comment]
@dkovalenko That change should be in 0.3.0.

**Comment by dkovalenko** [comment]
I tried 0.3.0 and had an error with BSONObjectID parsing.

https://scastie.scala-lang.org/Npc3sedMQY66cAiHsLRELw

`Left(reactivemongo.bson.exceptions.TypeDoesNotMatch: Cannot convert BSONObjectID("5cb849955e41a4e601b07837"): class reactivemongo.bson.BSONObjectID to io.circe.Json with io.circe.bson)`

**Comment by travisbrown** [comment]
@dkovalenko Ah, you're right. I can publish a quick 0.3.1 today, but if you're using this project are you interested in joining as a maintainer? I'm no longer using it since I left Stripe, so it's extremely low on my list of priorities.

**Comment by travisbrown** [comment]
@dkovalenko 0.3.1 is out.
